-- Cancellazione tabella TIMER e relativi vincoli
DROP SEQUENCE IF EXISTS TIMER_SEQUENCE;
ALTER TABLE IF EXISTS TIMER DROP CONSTRAINT TIMER_PK;
ALTER TABLE IF EXISTS TIMER DROP CONSTRAINT TIMER_JOB_NAME_IDX;
ALTER TABLE IF EXISTS TIMER DROP CONSTRAINT TIMER_JOB_CLASS_IDX;
DROP TABLE IF EXISTS TIMER;

-- Creazione tabella TIMER e relativi vincoli
CREATE TABLE TIMER 
(	
	"JOB_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(30 BYTE), 
	"JOB_GROUP" VARCHAR2(30 BYTE), 
	"JOB_STATUS" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"JOB_CLASS" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"CRON_EXPRESSION" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"INTERFACE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"REPEAT_TIME" NUMBER DEFAULT NULL, 
	"CRON_JOB" CHAR(1 BYTE) DEFAULT 'N', 
	"ENABLED" CHAR(1 BYTE), 
	"LAST_EXECUTION_STATUS" VARCHAR2(20 CHAR), 
	"LAST_START" TIMESTAMP (6), 
	"LAST_STOP" TIMESTAMP (6)
);
ALTER TABLE TIMER ADD CONSTRAINT TIMER_PK PRIMARY KEY ("JOB_ID");
ALTER TABLE TIMER ADD CONSTRAINT TIMER_JOB_NAME_IDX UNIQUE ("JOB_NAME");
ALTER TABLE TIMER ADD CONSTRAINT TIMER_JOB_CLASS_IDX UNIQUE ("JOB_CLASS");
CREATE SEQUENCE TIMER_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
