-- Aggiunta campo tabella TIPS_CAMT_052_BANK_ACCOUNT_REPORT
CREATE TABLE "BICOMP"."TIPS_CAMT_052_BANK_ACCOUNT_REPORT" 
(	
    "ID" NUMBER,
	"TMS_INSERT" TIMESTAMP (6), 
	"REPORT_NAME" VARCHAR2(100 BYTE),
	"MSG_ID" VARCHAR2(35 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (6),
	"ACCOUNT_ID" VARCHAR2(30 BYTE),
	"CURRENCY" CHAR(3 CHAR),
	"ACCOUNT_OWNER" VARCHAR2(11 BYTE),
	"SETTLEMENT_DATE" DATE,
	"OPENING_BALANCE" NUMBER(18, 2),
	"CLOSING_BALANCE" NUMBER(18, 2),
	"TOTAL_CREDIT_OPERATION" NUMBER(18, 2),
	"TOTAL_DEBIT_OPERATION" NUMBER(18, 2),
    
    CONSTRAINT TIPS_CAMT_052_BANK_ACCOUNT_REPORT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE  "BICOMP"."TIPS_CAMT_052_BANK_ACCOUNT_REPORT_SEQUENCE"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;