-- Aggiunta indice a tabella RT1_PSR_FILE_HEADER
ALTER TABLE "BICOMP"."RT1_PSR_FILE_HEADER" ADD CONSTRAINT "RT1_PSR_FILE_HEADER_REPORT_NAME_IDX" UNIQUE ("REPORT_NAME");


-- Rimozione colonna da tabella RT1_PSR_FILE_HEADER
ALTER TABLE "BICOMP"."RT1_PSR_FILE_HEADER"
DROP COLUMN DATE_TIME;


-- Aggiunta colonna a tabella RT1_PSR_FILE_HEADER
ALTER TABLE "BICOMP"."RT1_PSR_FILE_HEADER"
ADD DATE_TIME TIMESTAMP(6);
