-- Cancellazione tabella CGS_CAMT_053_SERVICE_PAYMENTS e relativi vincoli
DROP SEQUENCE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS_SEQUENCE";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_FK_SERVICE_STATEMENT";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PAYMENT_REFERENCE_SIDE_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PK";
DROP TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS";


-- Cancellazione tabella CGS_CAMT_053_SERVICE_STATEMENT e relativi vincoli
DROP SEQUENCE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT_SEQUENCE";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_FK_BULK";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_SERVICE_STATEMENT_ID_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_MESSAGE_ID_SERVICE_STATEMENT_ID_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_PK";
DROP TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT";


-- Cancellazione tabella CGS_CAMT_053_ACCOUNT_STATEMENT e relativi vincoli
DROP SEQUENCE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE";
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_FK_BULK";
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_ACCOUNT_STATEMENT_ID_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_MESSAGE_ID_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_PK";
DROP TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT";


-- Cancellazione tabella CGS_CAMT_053_BULK e relativi vincoli
DROP SEQUENCE "BICOMP"."CGS_CAMT_053_BULK_SEQUENCE";
ALTER TABLE "BICOMP"."CGS_CAMT_053_BULK" DROP CONSTRAINT "CGS_CAMT_053_BULK_FILE_REF_IDX";
ALTER TABLE "BICOMP"."CGS_CAMT_053_BULK" DROP CONSTRAINT "CGS_CAMT_053_BULK_PK";
DROP TABLE "BICOMP"."CGS_CAMT_053_BULK";