-- Rimozione index tabella CGS_LMR_PLCR_BULK_STATEMENT_ENTRY
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" DROP CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX";

-- Aggiunta index tabella CGS_LMR_PLCR_BULK_STATEMENT_ENTRY
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX" 
	UNIQUE ("ENTRY_REFERENCE", "SIDE", "LMR_PLCR_BULK_STATEMENT_ID");