-- Creazione tabella CGS_CAMT_053_BULK e relativi vincoli
CREATE TABLE "BICOMP"."CGS_CAMT_053_BULK" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"REPORT_NAME" VARCHAR2(50 CHAR),
	"SENDING_INSTITUTE" VARCHAR2(11 CHAR), 
	"RECEIVING_INSTITUTE" VARCHAR2(11 CHAR), 
	"SERVICE_ID" CHAR(3 BYTE), 
    "ENVIRONMENT" CHAR(1 BYTE),
	"FILE_TYPE" CHAR(3 BYTE), 
	"FILE_REF" VARCHAR2(30 CHAR), 
	"FILE_SETTLEMENT_DATE" DATE, 
	"FILE_LAC" CHAR(2 BYTE), 
	"FILE_CREATION_DATE_TIME" TIMESTAMP (6)
);
ALTER TABLE "BICOMP"."CGS_CAMT_053_BULK" ADD CONSTRAINT "CGS_CAMT_053_BULK_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_BULK" ADD CONSTRAINT "CGS_CAMT_053_BULK_FILE_REF_IDX" UNIQUE ("FILE_REF");
CREATE SEQUENCE "BICOMP"."CGS_CAMT_053_BULK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_CAMT_053_ACCOUNT_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
    "MESSAGE_ID" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
	"ACCOUNT_STATEMENT_ID" VARCHAR2(100 CHAR),
    "FROM_DATE_TIME" TIMESTAMP (6),
    "TO_DATE_TIME" TIMESTAMP (6),
    "CASH_ACCOUNT_OWNER" VARCHAR2(11 CHAR),
    "OPENING_BALANCE" NUMBER(18,2),
    "OPENING_BALANCE_SIDE" CHAR(1 BYTE),
    "CLOSING_BALANCE" NUMBER(18,2), 
    "CLOSING_BALANCE_SIDE" CHAR(1 BYTE),
    "SETTLEMENT_DATE" DATE,
    "BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_MESSAGE_ID_IDX" UNIQUE ("MESSAGE_ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_ACCOUNT_STATEMENT_ID_IDX" UNIQUE ("ACCOUNT_STATEMENT_ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_ACCOUNT_STATEMENT_FK_BULK" FOREIGN KEY ("BULK_ID") REFERENCES "BICOMP"."CGS_CAMT_053_BULK"("ID");
CREATE SEQUENCE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_CAMT_053_SERVICE_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
    "MESSAGE_ID" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
	"SERVICE_STATEMENT_ID" VARCHAR2(100 CHAR),
	"SERVICE" CHAR(3 BYTE),
    "FROM_DATE_TIME" TIMESTAMP (6),
    "TO_DATE_TIME" TIMESTAMP (6),
    "CASH_ACCOUNT_OWNER" VARCHAR2(11 CHAR),
    "DEBIT_SETTLEMENT_AMOUNT" NUMBER(18,2),
    "CREDIT_SETTLEMENT_AMOUNT" NUMBER(18,2),
    "SETTLEMENT_DATE" DATE,
    "BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_MESSAGE_ID_SERVICE_STATEMENT_ID_IDX" UNIQUE ("MESSAGE_ID", "SERVICE_STATEMENT_ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_SERVICE_STATEMENT_ID_IDX" UNIQUE ("SERVICE_STATEMENT_ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_STATEMENT_FK_BULK" FOREIGN KEY ("BULK_ID") REFERENCES "BICOMP"."CGS_CAMT_053_BULK"("ID");
CREATE SEQUENCE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_CAMT_053_SERVICE_PAYMENTS e relativi vincoli
CREATE TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
    "PAYMENT_REFERENCE" VARCHAR2(100 CHAR),
    "PAYMENT_AMOUNT" NUMBER(18,2),
    "CURRENCY" CHAR(3 BYTE),
	"SETTLEMENT_DATE_TIME" TIMESTAMP (6),
	"SIDE" CHAR(1 BYTE),
    "STATUS" VARCHAR2(10 CHAR),
    "DEBITOR_BIC" VARCHAR2(11 CHAR),
    "CREDITOR_BIC" VARCHAR2(11 CHAR),
    "SERVICE_STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PAYMENT_REFERENCE_SIDE_IDX" UNIQUE ("PAYMENT_REFERENCE", "SIDE");
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_FK_SERVICE_STATEMENT" FOREIGN KEY ("SERVICE_STATEMENT_ID") REFERENCES "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT"("ID");
CREATE SEQUENCE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;