-- Rimozione campo EXCEPTION_MESSAGE da tabella TIMER
ALTER TABLE "BICOMP"."TIMER" DROP COLUMN EXCEPTION_MESSAGE;

-- Rimozione campo REPEAT_TIME da tabella TIMER
ALTER TABLE "BICOMP"."TIMER" DROP COLUMN REPEAT_TIME;

-- Creazione tabella EVENT
CREATE TABLE "BICOMP"."EVENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"DESCRIZIONE" CLOB
);
ALTER TABLE "BICOMP"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID");
CREATE SEQUENCE "BICOMP"."EVENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
