-- Cancellazione indice dalla tabella CGS_CAMT_053_SERVICE_PAYMENTS
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" DROP CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PAYMENT_REFERENCE_SIDE_IDX";

-- Creazione nuovo indice
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_PAYMENTS" ADD CONSTRAINT "CGS_CAMT_053_SERVICE_PAYMENTS_PAYMENT_REFERENCE_SIDE_SERVICE_STATEMENT_ID_IDX" UNIQUE ("PAYMENT_REFERENCE", "SIDE", "SERVICE_STATEMENT_ID");