-- Creazione tabella CGS_LMR_PLCR_BULK
CREATE TABLE "BICOMP"."CGS_LMR_PLCR_BULK" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"BULK_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "LMR_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_FK" FOREIGN KEY ("LMR_ID") REFERENCES "BICOMP"."CGS_LMR"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_BULK_REFERENCE_IDX" UNIQUE ("BULK_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_PLCR_BULK_STATEMENT
CREATE TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"STATEMENT_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "FROM_DATE_TIME" TIMESTAMP (6),
    "TO_DATE_TIME" TIMESTAMP (6),
    "ACCOUNT_OWNER" VARCHAR2(11 CHAR),
	"CREDIT_PAYMENTS" NUMBER(18,2),
	"DEBIT_PAYMENTS" NUMBER(18,2),
	"PENDING_PAYMENTS" NUMBER(18,2),
    "SETTLEMENT_DATE" DATE,
	"LMR_PLCR_BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_FK" FOREIGN KEY ("LMR_PLCR_BULK_ID") REFERENCES "BICOMP"."CGS_LMR_PLCR_BULK"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_STATEMENT_REFERENCE_IDX" UNIQUE ("STATEMENT_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_PLCR_BULK_STATEMENT_ENTRY
CREATE TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"ENTRY_REFERENCE" VARCHAR2(100 CHAR),
    "PAYMENT_AMOUNT" NUMBER(18,2),
    "CURRENCY" CHAR(3 BYTE),
	"SETTLEMENT_DATE_TIME" TIMESTAMP (6),
	"SIDE" CHAR(1 BYTE),
    "STATUS" VARCHAR2(10 CHAR),
    "DEBITOR_BIC" VARCHAR2(11 CHAR),
    "CREDITOR_BIC" VARCHAR2(11 CHAR),
	"ADDITIONAL_INFO" VARCHAR2(100 CHAR),
	"LMR_PLCR_BULK_STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_FK" FOREIGN KEY ("LMR_PLCR_BULK_STATEMENT_ID") REFERENCES "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX" UNIQUE ("ENTRY_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;