-- Modifica nomi colonne tabella TIMER
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "JOB_ID" TO "ID";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "JOB_NAME" TO "NAME";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "JOB_GROUP" TO "GROUP";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "JOB_STATUS" TO "STATUS";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "JOB_CLASS" TO "CLASS_NAME";


-- Rimozione indici tabella TIMER
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_PK";
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_JOB_NAME_IDX";
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_JOB_CLASS_IDX";


-- Creazione indici tabella TIMER
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_NAME_IDX" UNIQUE ("NAME");
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_CLASS_NAME_IDX" UNIQUE ("CLASS_NAME");
