-- Creazione tabella CGS_LMR
CREATE TABLE "BICOMP"."CGS_LMR" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"SETTLEMENT_BIC" VARCHAR2(11 CHAR),
	"REPORT_NAME" VARCHAR2(50 CHAR),
	"SENDING_INSTITUTE" VARCHAR2(11 CHAR), 
	"RECEIVING_INSTITUTE" VARCHAR2(11 CHAR), 
	"SERVICE_ID" CHAR(3 BYTE), 
    "ENVIRONMENT" CHAR(1 BYTE),
	"FILE_TYPE" CHAR(3 BYTE), 
	"FILE_REF" VARCHAR2(30 CHAR), 
	"FILE_SETTLEMENT_DATE" DATE, 
	"FILE_LAC" CHAR(2 BYTE), 
	"FILE_CREATION_DATE_TIME" TIMESTAMP (6)
);
ALTER TABLE "BICOMP"."CGS_LMR" ADD CONSTRAINT "CGS_LMR_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR" ADD CONSTRAINT "CGS_LMR_FILE_REF_IDX" UNIQUE ("FILE_REF");
CREATE SEQUENCE "BICOMP"."CGS_LMR_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_LAC_BULK
CREATE TABLE "BICOMP"."CGS_LMR_LAC_BULK" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"BULK_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "LMR_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK" ADD CONSTRAINT "CGS_LMR_LAC_BULK_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK" ADD CONSTRAINT "CGS_LMR_LAC_BULK_FK" FOREIGN KEY ("LMR_ID") REFERENCES "BICOMP"."CGS_LMR"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK" ADD CONSTRAINT "CGS_LMR_LAC_BULK_BULK_REFERENCE_IDX" UNIQUE ("BULK_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_LAC_BULK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_LAC_BULK_STATEMENT
CREATE TABLE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"STATEMENT_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "FROM_DATE_TIME" TIMESTAMP (6),
    "TO_DATE_TIME" TIMESTAMP (6),
    "ACCOUNT_OWNER" VARCHAR2(11 CHAR),
    "OPENING_BALANCE" NUMBER(18,2),
    "OPENING_BALANCE_SIDE" CHAR(1 BYTE),
    "CLOSING_BALANCE" NUMBER(18,2), 
    "CLOSING_BALANCE_SIDE" CHAR(1 BYTE),
	"CREDIT_LIQUIDITY_TRANSFER" NUMBER(18,2),
	"DEBIT_LIQUIDITY_TRANSFER" NUMBER(18,2),
	"CREDIT_PAYMENTS" NUMBER(18,2),
	"DEBIT_PAYMENTS" NUMBER(18,2),
    "SETTLEMENT_DATE" DATE,
	"LMR_LAC_BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LAC_BULK_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LAC_BULK_STATEMENT_FK" FOREIGN KEY ("LMR_LAC_BULK_ID") REFERENCES "BICOMP"."CGS_LMR_LAC_BULK"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LAC_BULK_STATEMENT_STATEMENT_REFERENCE_IDX" UNIQUE ("STATEMENT_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_LTIN_BULK
CREATE TABLE "BICOMP"."CGS_LMR_LTIN_BULK" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"BULK_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "LMR_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_FK" FOREIGN KEY ("LMR_ID") REFERENCES "BICOMP"."CGS_LMR"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_BULK_REFERENCE_IDX" UNIQUE ("BULK_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_LTIN_BULK_STATEMENT
CREATE TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"STATEMENT_REFERENCE" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
    "FROM_DATE_TIME" TIMESTAMP (6),
    "TO_DATE_TIME" TIMESTAMP (6),
    "ACCOUNT_OWNER" VARCHAR2(11 CHAR),
	"CREDIT_LIQUIDITY_TRANSFER" NUMBER(18,2),
	"DEBIT_LIQUIDITY_TRANSFER" NUMBER(18,2),
    "SETTLEMENT_DATE" DATE,
	"LMR_LTIN_BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_FK" FOREIGN KEY ("LMR_LTIN_BULK_ID") REFERENCES "BICOMP"."CGS_LMR_LTIN_BULK"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_STATEMENT_REFERENCE_IDX" UNIQUE ("STATEMENT_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella CGS_LMR_LTIN_BULK_STATEMENT_ENTRY
CREATE TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"ENTRY_REFERENCE" VARCHAR2(100 CHAR),
    "PAYMENT_AMOUNT" NUMBER(18,2),
    "CURRENCY" CHAR(3 BYTE),
	"SETTLEMENT_DATE_TIME" TIMESTAMP (6),
	"SIDE" CHAR(1 BYTE),
    "STATUS" VARCHAR2(10 CHAR),
    "DEBITOR_BIC" VARCHAR2(11 CHAR),
    "CREDITOR_BIC" VARCHAR2(11 CHAR),
	"ADDITIONAL_INFO" VARCHAR2(100 CHAR),
	"LMR_LTIN_BULK_STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_ENTRY_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_ENTRY_FK" FOREIGN KEY ("LMR_LTIN_BULK_STATEMENT_ID") REFERENCES "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT"("ID");
ALTER TABLE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY" ADD CONSTRAINT "CGS_LMR_LTIN_BULK_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX" UNIQUE ("ENTRY_REFERENCE");
CREATE SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;