-- Rimozione campo MATRICOLA da tabella FEEDBACK
ALTER TABLE "BICOMP"."FEEDBACK"
DROP COLUMN MATRICOLA;

-- Aggiunta campi TMS_INSERT e TMS_UPDATED a tabella FEEDBACK
ALTER TABLE "BICOMP"."FEEDBACK"
ADD (
	INSERT_USER NUMBER,
	UPDATE_USER NUMBER,
	TMS_INSERT TIMESTAMP(6),
	TMS_UPDATE TIMESTAMP(6)
);
