-- Aggiunta indice tabella TIPS_CAMT_052_BANK_ACCOUNT_REPORT
ALTER TABLE "BICOMP"."TIPS_CAMT_052_BANK_ACCOUNT_REPORT"
ADD CONSTRAINT "TIPS_CAMT_052_BANK_ACCOUNT_REPORT_REPORT_NAME_IDX" UNIQUE ("REPORT_NAME");
