-- Cancellazione tabella USERS_ROLE e relativi vincoli
ALTER TABLE "BICOMP"."USERS_ROLE" DROP CONSTRAINT "USERS_ROLE_PK";
DROP TABLE "BICOMP"."USERS_ROLE";

-- Creazione tabella USERS_ROLE e relativi vincoli
CREATE TABLE "BICOMP"."USERS_ROLE" 
(
	"USERS_ID" NUMBER, 
	"ROLE_ID" NUMBER
);
ALTER TABLE "BICOMP"."USERS_ROLE" ADD CONSTRAINT "USERS_ROLE_PK" PRIMARY KEY ("USERS_ID", "ROLE_ID");