-- Rinomina campi tabella CGS_CAMT_053_SERVICE_STATEMENT
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT"
RENAME COLUMN DEBIT_SETTLEMENT_AMOUNT TO DEBIT_SETTLED_AMOUNT;

ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT"
RENAME COLUMN CREDIT_SETTLEMENT_AMOUNT TO CREDIT_SETTLED_AMOUNT;


-- Aggiunta campi tabella CGS_CAMT_053_SERVICE_STATEMENT
ALTER TABLE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT"
ADD DEBIT_PENDING_AMOUNT NUMBER(18,2);
