-- Aggiunta campo tabella TIPS_CAMT_053_BANK_STATEMENT
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" ADD "TMS_INSERT" TIMESTAMP (6);


-- Aggiunta campo tabella TIPS_CAMT_053_ACCOUNT_STATEMENT
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT" ADD "TMS_INSERT" TIMESTAMP (6);


-- Aggiunta campo tabella TIPS_CAMT_053_ACCOUNT_PAYMENTS
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" ADD "TMS_INSERT" TIMESTAMP (6);
