-- Cancellazione tabella TIPS_CAMT_053_ACCOUNT_PAYMENTS e relativi vincoli
--DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS_SEQUENCE";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" DROP CONSTRAINT "BNK_TO_CSTM_STMT_ENTRY_PK";
--DROP TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS";

-- Cancellazione tabella TIPS_CAMT_053_ACCOUNT_STATEMENT e relativi vincoli
--DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "TIPS_CAMT_053_ACCOUNT_STATEMENT_PK";
--DROP TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT";

-- Cancellazione tabella TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT e relativi vincoli
--DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_SEQUENCE";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" DROP CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_PK";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" DROP CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX";
--DROP TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY";

-- Cancellazione tabella TIPS_CAMT_053_BANK_STATEMENT e relativi vincoli
--DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT_SEQUENCE";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" DROP CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_PK";
--ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" DROP CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_MSG_ID_IDX";
--DROP TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT";

-- Cancellazione tabella TIPS_BUSINESS_DAY e relativi vincoli
--DROP SEQUENCE "BICOMP"."TIPS_BUSINESS_DAY_SEQUENCE";
--ALTER TABLE "BICOMP"."TIPS_BUSINESS_DAY" DROP CONSTRAINT "TIPS_BUSINESS_DAY_PK";
--DROP TABLE "BICOMP"."TIPS_BUSINESS_DAY";


-- Creazione tabella TIPS_CAMT_053_BANK_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" 
(	
	"ID" NUMBER, 
	"MSG_ID" VARCHAR2(35 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (2)
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_MSG_ID_IDX" UNIQUE ("MSG_ID");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella TIPS_CAMT_053_ACCOUNT_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT" 
(	
	"ID" NUMBER, 
	"STMT_ID" VARCHAR2(35 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (2), 
	"FROM_DATE_TIME" TIMESTAMP (2), 
	"TO_DATE_TIME" TIMESTAMP (2), 
	"ACCOUNT_ID" VARCHAR2(34 BYTE), 
	"CURRENCY" CHAR(3 BYTE), 
	"OWNER_BIC" CHAR(11 BYTE), 
	"SETTLEMENT_DATE" DATE, 
	"CLOSING_BALANCE" NUMBER(18,2), 
	"BALANCE_INDICATOR" CHAR(4 BYTE), 
	"STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_ACCOUNT_STATEMENT_PK" PRIMARY KEY ("ID");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella TIPS_CAMT_053_ACCOUNT_PAYMENTS e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" 
(	
	"ID" NUMBER, 
	"TRANSACTION_REFERENCE" VARCHAR2(35 BYTE), 
	"SETTLEMENT_DATE_TIME" TIMESTAMP (2), 
	"AMOUNT" NUMBER(18,2), 
	"CURRENCY" CHAR(3 BYTE), 
	"TRANSACTION_STATUS" CHAR(4 BYTE), 
	"SIDE" CHAR(4 BYTE), 
	"BANK_TRANSACTION_CODE" CHAR(4 BYTE), 
	"BANK_TRANSACTION_CODE_FAMILY" CHAR(4 BYTE), 
	"DEBITOR_BIC" CHAR(11 BYTE), 
	"CREDITOR_BIC" CHAR(11 BYTE), 
	"STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" ADD CONSTRAINT "TIPS_CAMT_053_ACCOUNT_PAYMENTS_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" ADD CONSTRAINT "TIPS_CAMT_053_ACCOUNT_PAYMENTS_TRANSACTION_REFERENCE_IDX" UNIQUE ("TRANSACTION_REFERENCE");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella TIPS_BUSINESS_DAY e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_BUSINESS_DAY" 
(	
	"ID" NUMBER, 
	"BUSINESS_DAY" DATE, 
	"BUSINESS_DAY_TYPE" VARCHAR2(4 BYTE), 
	"FROM_DATE" TIMESTAMP (2), 
	"TO_DATE" TIMESTAMP (2)
);
ALTER TABLE "BICOMP"."TIPS_BUSINESS_DAY" ADD CONSTRAINT "TIPS_BUSINESS_DAY_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_BUSINESS_DAY" ADD CONSTRAINT "TIPS_BUSINESS_DAY_BUSINESS_DAY_IDX" UNIQUE ("BUSINESS_DAY");
CREATE SEQUENCE "BICOMP"."TIPS_BUSINESS_DAY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
