-- Creazione tabella FEEDBACK_EVENTI
CREATE TABLE "BICOMP"."FEEDBACK_EVENTI" 
(	
	"ID" NUMBER,
	"DESCRIZIONE" VARCHAR2(200 BYTE),
	"TMS_INSERT" TIMESTAMP (6),
	"FEEDBACK_ID" NUMBER
);
ALTER TABLE "BICOMP"."FEEDBACK_EVENTI" ADD CONSTRAINT "FEEDBACK_EVENTI_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."FEEDBACK_EVENTI" ADD CONSTRAINT "FEEDBACK_EVENTI_FK" FOREIGN KEY ("FEEDBACK_ID") REFERENCES "BICOMP"."FEEDBACK"("ID");
CREATE SEQUENCE "BICOMP"."FEEDBACK_EVENTI_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
