-- Cancellazione tabella TIPS_CAMT_053_ACCOUNT_PAYMENTS e relativi vincoli
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS_SEQUENCE";
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" DROP CONSTRAINT "TIPS_CAMT_053_ACCOUNT_PAYMENTS_PK";
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS" DROP CONSTRAINT "TIPS_CAMT_053_ACCOUNT_PAYMENTS_TRANSACTION_REFERENCE_IDX";
DROP TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_PAYMENTS";

-- Cancellazione tabella TIPS_CAMT_053_ACCOUNT_STATEMENT e relativi vincoli
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE";
ALTER TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT" DROP CONSTRAINT "TIPS_CAMT_053_ACCOUNT_STATEMENT_PK";
DROP TABLE "BICOMP"."TIPS_CAMT_053_ACCOUNT_STATEMENT";

-- Cancellazione tabella TIPS_CAMT_053_BANK_STATEMENT e relativi vincoli
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT_SEQUENCE";
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" DROP CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_PK";
DROP TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT";


-- Creazione tabella TIPS_CAMT_053_BANK_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" 
(	
	"ID" NUMBER,
	"TMS_INSERT" TIMESTAMP (6), 
	"REPORT_NAME" VARCHAR2(100 BYTE),
	"MSG_ID" VARCHAR2(35 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (6)
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_STATEMENT_MSG_ID_IDX" UNIQUE ("MSG_ID");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT" 
(	
	"ID" NUMBER,
	"TMS_INSERT" TIMESTAMP (6),
	"STMT_ID" VARCHAR2(35 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (6), 
	"FROM_DATE_TIME" TIMESTAMP (6),
	"TO_DATE_TIME" TIMESTAMP (6),
	"ACCOUNT_NUMBER" VARCHAR2(34 BYTE), 
	"ACCOUNT_OWNER" CHAR(11 BYTE), 
	"SETTLEMENT_DATE" DATE, 
	"CLOSING_BALANCE" NUMBER(18,2), 
	"BALANCE_INDICATOR" CHAR(1 BYTE), 
	"BANK_STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT" ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_FK" FOREIGN KEY ("BANK_STATEMENT_ID") REFERENCES "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT"("ID");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY e relativi vincoli
CREATE TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" 
(	
	"ID" NUMBER,
	"TMS_INSERT" TIMESTAMP (6),
	"ENTRY_REFERENCE" VARCHAR2(35 BYTE), 
	"SETTLEMENT_DATE_TIME" TIMESTAMP (6),
	"PAYMENT_AMOUNT" NUMBER(18,2), 
	"CURRENCY" CHAR(3 BYTE), 
	"STATUS" CHAR(4 BYTE), 
	"SIDE" CHAR(1 BYTE), 
	"BANK_TRANSACTION_CODE" CHAR(4 BYTE), 
	"BANK_TRANSACTION_CODE_FAMILY" CHAR(4 BYTE), 
	"DEBITOR_BIC" CHAR(11 BYTE), 
	"CREDITOR_BIC" CHAR(11 BYTE), 
	"BANK_ACCOUNT_STATEMENT_ID" NUMBER
);
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_FK" FOREIGN KEY ("BANK_ACCOUNT_STATEMENT_ID") REFERENCES "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT"("ID");
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY" ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX" UNIQUE ("ENTRY_REFERENCE");
CREATE SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
