-- Cancellazione tabella USERS_ROLE e relativi vincoli
--ALTER TABLE "BICOMP"."USERS_ROLE" DROP CONSTRAINT "USERS_ROLE_PK";
--DROP TABLE "BICOMP"."USERS_ROLE";

-- Cancellazione tabella USERS e relativi vincoli
--DROP SEQUENCE "BICOMP"."USERS_SEQUENCE";
--ALTER TABLE "BICOMP"."USERS" DROP CONSTRAINT "BICOMP_USERS_PK";
--ALTER TABLE "BICOMP"."USERS" DROP CONSTRAINT "REGISTRATION_NUMBER_IDX";
--DROP TABLE "BICOMP"."USERS";

-- Cancellazione tabella ROLE e relativi vincoli
--DROP SEQUENCE "BICOMP"."ROLE_SEQUENCE";
--ALTER TABLE "BICOMP"."ROLE" DROP CONSTRAINT "ROLE_PK";
--DROP TABLE "BICOMP"."ROLE";


-- Creazione tabella USERS e relativi vincoli
CREATE TABLE "BICOMP"."USERS" 
(	
	"ID" NUMBER, 
	"REGISTRATION_NUMBER" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"CREATION_DATE_TIME" TIMESTAMP (2), 
	"LAST_LOGIN_DATE_TIME" TIMESTAMP (2), 
	"CODICE_AREA_DIPENDENZA" VARCHAR2(10 BYTE), 
	"CODICE_DIPENDENZA" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"MOBILE_PHONE" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(30 CHAR)
);
ALTER TABLE "BICOMP"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."USERS" ADD CONSTRAINT "USERS_REGISTRATION_NUMBER_IDX" UNIQUE ("REGISTRATION_NUMBER");
CREATE SEQUENCE "BICOMP"."USERS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella ROLE e relativi vincoli
CREATE TABLE "BICOMP"."ROLE" 
(	
	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
);
ALTER TABLE "BICOMP"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."ROLE" ADD CONSTRAINT "ROLE_NAME_IDX" UNIQUE ("NAME");
CREATE SEQUENCE "BICOMP"."ROLE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- Creazione tabella USERS_ROLE e relativi vincoli
CREATE TABLE "BICOMP"."USERS_ROLE" 
(
	"USERS_ID" NUMBER, 
	"ROLE_ID" NUMBER
);
ALTER TABLE "BICOMP"."USERS_ROLE" ADD CONSTRAINT "USERS_ROLE_PK" PRIMARY KEY ("USERS_ID", "ROLE_ID");