-- Creazione tabella RT1_BULK
CREATE TABLE "BICOMP"."RT1_BULK" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"SENDING_INSTITUTE" VARCHAR2(11 CHAR),
	"RECEIVING_INSTITUTE" VARCHAR2(11 CHAR),
	"ENV_INDICATOR" CHAR(1 BYTE),
	"FILE_TYPE" CHAR(3 BYTE),
	"FILE_REFERENCE" VARCHAR2(30 CHAR),
	"FILE_DATE" DATE,
	"FILE_CYCLE" CHAR(2 BYTE)
);
ALTER TABLE "BICOMP"."RT1_BULK" ADD CONSTRAINT "RT1_BULK_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_BULK" ADD CONSTRAINT "RT1_BULK_FILE_REFERENCE_IDX" UNIQUE ("FILE_REFERENCE");
CREATE SEQUENCE "BICOMP"."RT1_BULK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella RT1_BULK_PAYMENT
CREATE TABLE "BICOMP"."RT1_BULK_PAYMENT" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"MSG_ID" VARCHAR2(100 CHAR),
	"CREATION_DATE_TIME" TIMESTAMP (6),
	"ORIGINAL_MSG_ID" VARCHAR2(50 CHAR),
	"ORIGINAL_MSG_NAME" VARCHAR2(20 CHAR),
	"ORIGINAL_TRANSACTION_NUMBER" NUMBER,
	"ORIGINAL_AMOUNT" NUMBER(18,2),
	"STATUS" CHAR(4 BYTE),
	"REJECT_REASON" VARCHAR2(10 CHAR),
	"STATUS_ID" VARCHAR2(50 CHAR),
	"ORIGINAL_INSTRUCTION_ID" VARCHAR2(50 CHAR),
	"ORIGINAL_END_TO_END_ID" VARCHAR2(50 CHAR),
	"ORIGINAL_TRANSACTION_ID" VARCHAR2(50 CHAR),
	"ACCEPTANCE_DATE_TIME" TIMESTAMP(6),
	"PAYMENT_AMOUNT" NUMBER(18,2),
	"SETTLEMENT_DATE" DATE,
	"DEBITOR" VARCHAR2(11 CHAR),
	"CREDITOR" VARCHAR2(11 CHAR),
	"RT1_BULK_ID" NUMBER
);
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT" ADD CONSTRAINT "RT1_BULK_PAYMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT" ADD CONSTRAINT "RT1_BULK_FK" FOREIGN KEY ("RT1_BULK_ID") REFERENCES "BICOMP"."RT1_BULK"("ID");
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT" ADD CONSTRAINT "RT1_BULK_PAYMENT_MSG_ID_IDX" UNIQUE ("MSG_ID");
CREATE SEQUENCE "BICOMP"."RT1_BULK_PAYMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
