-- Modifica nomi colonne tabella TIMER
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "ID" TO "JOB_ID";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "NAME" TO "JOB_NAME";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "GROUP" TO "JOB_GROUP";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "STATUS" TO "JOB_STATUS";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "CLASS" TO "JOB_CLASS";
ALTER TABLE "BICOMP"."TIMER" RENAME COLUMN "DESCRIPTION" TO "JOB_DESCRIPTION";


-- Rimozione indici tabella TIMER
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_PK";
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_NAME_IDX";
ALTER TABLE "BICOMP"."TIMER" DROP CONSTRAINT "TIMER_CLASS_NAME_IDX";


-- Creazione indici tabella TIMER
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_PK" PRIMARY KEY ("JOB_ID");
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_JOB_NAME_IDX" UNIQUE ("JOB_NAME");
ALTER TABLE "BICOMP"."TIMER" ADD CONSTRAINT "TIMER_JOB_CLASS_IDX" UNIQUE ("JOB_CLASS");
