-- Rimozione tabella USERS_ROLE
ALTER TABLE "BICOMP"."USERS_ROLE" DROP CONSTRAINT "USERS_ROLE_PK";
DROP TABLE "BICOMP"."USERS_ROLE";


-- Rimozione tabella ROLE
DROP SEQUENCE "BICOMP"."ROLE_SEQUENCE";
ALTER TABLE "BICOMP"."ROLE" DROP CONSTRAINT "ROLE_NAME_IDX";
ALTER TABLE "BICOMP"."ROLE" DROP CONSTRAINT "ROLE_PK";
DROP TABLE "BICOMP"."ROLE";