-- Creazione tabella RT1_PSR_FILE_HEADER
CREATE TABLE "BICOMP"."RT1_PSR_FILE_HEADER" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"SERVICE_IDENTIFIER" CHAR(3 BYTE),
	"FILE_TYPE" CHAR(3 BYTE),
	"SENDING_INSTITUTION" CHAR(8 BYTE),
	"SENDER_FILE_REFERENCE" CHAR(16 BYTE),
	"DATE_TIME" DATE,
	"TEST_CODE" CHAR(1 BYTE),
	"RECEIVING_INSTITUTION" CHAR(8 BYTE),
	"SETTLEMENT_DATE" DATE,
	"LAC" CHAR(2 BYTE),
	"RECORD_NUMBER" NUMBER
);
ALTER TABLE "BICOMP"."RT1_PSR_FILE_HEADER" ADD CONSTRAINT "RT1_PSR_FILE_HEADER_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_PSR_FILE_HEADER" ADD CONSTRAINT "RT1_PSR_FILE_HEADER_SENDER_FILE_REFERENCE_IDX" UNIQUE ("SENDER_FILE_REFERENCE");
CREATE SEQUENCE "BICOMP"."RT1_PSR_FILE_HEADER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella RT1_PSR_SETTLEMENT_BIC
CREATE TABLE "BICOMP"."RT1_PSR_SETTLEMENT_BIC" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"SETTLEMENT_BIC" CHAR(11 BYTE),
	"INITIAL_POSITION_INDICATOR" CHAR(2 BYTE),
	"INITIAL_LIQUIDITY_POSITION" NUMBER(18,2),
	"FINAL_POSITION_INDICATOR" CHAR(2 BYTE),
	"FINAL_LIQUIDITY_POSITION" NUMBER(18,2),
	"RT1_PSR_FILE_HEADER_ID" NUMBER UNIQUE
);
ALTER TABLE "BICOMP"."RT1_PSR_SETTLEMENT_BIC" ADD CONSTRAINT "RT1_PSR_SETTLEMENT_BIC_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_PSR_SETTLEMENT_BIC" ADD CONSTRAINT "RT1_PSR_SETTLEMENT_BIC_FK" FOREIGN KEY ("RT1_PSR_FILE_HEADER_ID") REFERENCES "BICOMP"."RT1_PSR_FILE_HEADER"("ID");
CREATE SEQUENCE "BICOMP"."RT1_PSR_SETTLEMENT_BIC_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
