-- Creazione tabella RT1_PSR_PARTICIPANT_HEADER
CREATE TABLE "BICOMP"."RT1_PSR_PARTICIPANT_HEADER" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"SETTLEMENT_BIC" CHAR(8 BYTE),
	"INITIAL_PART_POSITION_INDICATOR" CHAR(2 BYTE),
	"INITIAL_PART_POSITION" NUMBER(18,2),
	"FINAL_PART_POSITION_INDICATOR" CHAR(2 BYTE),
	"FINAL_PART_POSITION" NUMBER(18,2),
	"RECEIVED_FUNDING_AMOUNT" NUMBER(18,2),
	"REQUESTED_FUNDING_AMOUNT" NUMBER(18,2),
	"REQUESTED_DEFUNDING_AMOUNT" NUMBER(18,2),
	"REJECTED_DEFUNDING_AMOUNT" NUMBER(18,2),
	"CREDIT_LT_AMOUNT" NUMBER(18,2),
	"DEBIT_LT_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_SENT_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_RECEIVED_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_PENDING_AMOUNT" NUMBER(18,2),
	"REJECTED_PREV_PDNG_AMOUNT" NUMBER(18,2),
	"ACCEPTED_PREV_PDNG_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_RT1A_SENT_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_RT1A_RECEIVED_AMOUNT" NUMBER(18,2),
	"INSTANT_PRR_RT1A_PENDING_AMOUNT" NUMBER(18,2),
	"REJECTED_PREV_RT1A_PDNG_AMOUNT" NUMBER(18,2),
	"ACCEPTED_PREV_RT1A_PDNG_AMOUNT" NUMBER(18,2),
	"RT1_PSR_SETTLEMENT_BIC_ID" NUMBER
);
ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_HEADER" ADD CONSTRAINT "RT1_PSR_PARTICIPANT_HEADER_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_HEADER" ADD CONSTRAINT "RT1_PSR_PARTICIPANT_HEADER_FK" FOREIGN KEY ("RT1_PSR_SETTLEMENT_BIC_ID") REFERENCES "BICOMP"."RT1_PSR_SETTLEMENT_BIC"("ID");
CREATE SEQUENCE "BICOMP"."RT1_PSR_PARTICIPANT_HEADER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella RT1_PSR_PARTICIPANT_BODY
CREATE TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"OPERATION_TYPE" CHAR(4 BYTE),
	"LT_REFERENCE" CHAR(35 BYTE),
	"LT_AMOUNT" NUMBER(18,2),
	"LT_STATUS" CHAR(3 BYTE),
	"RT1_PSR_PARTICIPANT_HEADER_ID" NUMBER
);
ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY" ADD CONSTRAINT "RT1_PSR_PARTICIPANT_BODY_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY" ADD CONSTRAINT "RT1_PSR_PARTICIPANT_BODY_FK" FOREIGN KEY ("RT1_PSR_PARTICIPANT_HEADER_ID") REFERENCES "BICOMP"."RT1_PSR_PARTICIPANT_HEADER"("ID");
CREATE SEQUENCE "BICOMP"."RT1_PSR_PARTICIPANT_BODY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
