-- Modifica campo MESSAGE tabella NOTIFICATION
DROP SEQUENCE "BICOMP"."NOTIFICATION_SEQUENCE";
DROP TABLE "BICOMP"."NOTIFICATION";

CREATE TABLE "BICOMP"."NOTIFICATION" 
(	
    "ID" NUMBER, 
	"TMS_CREATE" TIMESTAMP (6),
	"MESSAGE" VARCHAR2(300 CHAR),
	"TMS_UPDATE" TIMESTAMP (6), 
	"UPDATE_USER" VARCHAR2(10 CHAR)
);
ALTER TABLE "BICOMP"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID");
CREATE SEQUENCE "BICOMP"."NOTIFICATION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
