-- Creazione tabella ISO_EXTERNAL_CODE_SET
CREATE TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"CODE_VALUE" VARCHAR2(4 CHAR),
	"CODE_NAME" VARCHAR2(150 CHAR), 
	"CODE_DESCRIPTION" VARCHAR2(400 CHAR)
);
ALTER TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET" ADD CONSTRAINT "ISO_EXTERNAL_CODE_SET_PK" PRIMARY KEY ("ID");
CREATE SEQUENCE "BICOMP"."ISO_EXTERNAL_CODE_SET_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
