-- Cancellazione tabella bridge NOTIFICATION_USERS
DROP TABLE "BICOMP"."NOTIFICATION_USERS";


-- Creazione tabella bridge NOTIFICATION_USER
CREATE TABLE "BICOMP"."NOTIFICATION_USER"
(	
    "NOTIFICATION_ID" NUMBER,
    "USER_ID" NUMBER,
    "TMS_READ" TIMESTAMP(6)
);
ALTER TABLE "BICOMP"."NOTIFICATION_USER" ADD CONSTRAINT "NOTIFICATION_USES_PK" PRIMARY KEY ("NOTIFICATION_ID", "USER_ID");
ALTER TABLE "BICOMP"."NOTIFICATION_USER" ADD CONSTRAINT "NOTIFICATION_USER_FK_NOTIFICATION" FOREIGN KEY ("NOTIFICATION_ID") REFERENCES "BICOMP"."NOTIFICATION"("ID");
ALTER TABLE "BICOMP"."NOTIFICATION_USER" ADD CONSTRAINT "NOTIFICATION_USER_FK_USER" FOREIGN KEY ("USER_ID") REFERENCES "BICOMP"."USERS"("ID");


-- Modifica tabella NOTIFICATION
ALTER TABLE "BICOMP"."NOTIFICATION"
DROP COLUMN TMS_UPDATE;
