-- Modifica tabella TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT"
ADD (
	OPENING_BALANCE NUMBER(18,2), 
	OPENING_BALANCE_INDICATOR CHAR(4 BYTE), 
	CLOSING_BALANCE_INDICATOR CHAR(4 BYTE)
);

UPDATE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT"
SET CLOSING_BALANCE_INDICATOR = BALANCE_INDICATOR;

ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT"
DROP COLUMN "BALANCE_INDICATOR";
