-- Aggiornamento valore campo SIDE tabella RT1_BULK_PAYMENT
UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE = 'C'
WHERE SIDE = 'CRDT';

UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE = 'D'
WHERE SIDE = 'DBIT';


-- Creo colonna temporanea SIDE_1 per cambio type colonna SIDE, imposto valori come colonna SIDE
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT"
ADD SIDE_1 CHAR(1 BYTE);

UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE_1 = 'C'
WHERE SIDE = 'C';

UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE_1 = 'D'
WHERE SIDE = 'D';


-- Rimuovo colonna SIDE
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT"
DROP COLUMN SIDE;


-- Creo nuova colonna SIDE con type CHAR
ALTER TABLE "BICOMP"."RT1_BULK_PAYMENT"
ADD SIDE CHAR(1 BYTE);


-- Imposto il valore di SIDE come SIDE_1
UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE = 'C'
WHERE SIDE_1 = 'C';

UPDATE "BICOMP"."RT1_BULK_PAYMENT"
SET SIDE = 'D'
WHERE SIDE_1 = 'D';