-- Rimozione tabella NOTIFICATION
DROP TABLE "BICOMP"."NOTIFICATION_USERS";
DROP SEQUENCE "BICOMP"."NOTIFICATION_SEQUENCE";
DROP TABLE "BICOMP"."NOTIFICATION";


-- Creazione tabella NOTIFICATION
CREATE TABLE "BICOMP"."NOTIFICATION" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"MESSAGE" CLOB,
	"LIVELLO" VARCHAR2(20 CHAR),
	"TMS_UPDATE" TIMESTAMP (6)
);
ALTER TABLE "BICOMP"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID");
CREATE SEQUENCE "BICOMP"."NOTIFICATION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella bridge NOTIFICATION_USERS
CREATE TABLE "BICOMP"."NOTIFICATION_USERS"
(	
    "NOTIFICATION_ID" NUMBER,
    "USERS_ID" NUMBER
);
ALTER TABLE "BICOMP"."NOTIFICATION_USERS" ADD CONSTRAINT "NOTIFICATION_USERS_PK" PRIMARY KEY ("NOTIFICATION_ID", "USERS_ID");
ALTER TABLE "BICOMP"."NOTIFICATION_USERS" ADD CONSTRAINT "NOTIFICATION_USERS_FK_NOTIFICATION" FOREIGN KEY ("NOTIFICATION_ID") REFERENCES "BICOMP"."NOTIFICATION"("ID");
ALTER TABLE "BICOMP"."NOTIFICATION_USERS" ADD CONSTRAINT "NOTIFICATION_USERS_FK_USERS" FOREIGN KEY ("USERS_ID") REFERENCES "BICOMP"."USERS"("ID");
