-- Rimozione tabella ISO_EXTERNAL_CODE_SET
DROP SEQUENCE "BICOMP"."ISO_EXTERNAL_CODE_SET_SEQUENCE";
DROP TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET";


-- Creazione tabella ISO_FILE e relativi vincoli
CREATE TABLE "BICOMP"."ISO_FILE" 
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
    "FILE_NAME" VARCHAR2(100 CHAR)
);
ALTER TABLE "BICOMP"."ISO_FILE" ADD CONSTRAINT "ISO_FILE_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."ISO_FILE" ADD CONSTRAINT "ISO_FILE_NAME_IDX" UNIQUE ("FILE_NAME");
CREATE SEQUENCE "BICOMP"."ISO_FILE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51696 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


-- Creazione tabella ISO_EXTERNAL_CODE_SET
CREATE TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET"
(	
    "ID" NUMBER, 
	"TMS_INSERT" TIMESTAMP (6),
	"CODE_VALUE" VARCHAR2(15 CHAR),
	"CODE_NAME" VARCHAR2(150 CHAR), 
	"CODE_DESCRIPTION" VARCHAR2(1000 CHAR),
	"ISO_FILE_ID" NUMBER
);
ALTER TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET" ADD CONSTRAINT "ISO_EXTERNAL_CODE_SET_PK" PRIMARY KEY ("ID");
ALTER TABLE "BICOMP"."ISO_EXTERNAL_CODE_SET" ADD CONSTRAINT "ISO_EXTERNAL_CODE_SET_FK_FILE" FOREIGN KEY ("ISO_FILE_ID") REFERENCES "BICOMP"."ISO_FILE"("ID");
CREATE SEQUENCE "BICOMP"."ISO_EXTERNAL_CODE_SET_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
