-- Rimozione indice TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX dalla tabella TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY
ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY"
DROP CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_ENTRY_REFERENCE_IDX";

ALTER TABLE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY"
ADD CONSTRAINT "TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_ENTRY_REFERENCE_SIDE_IDX" UNIQUE ("ENTRY_REFERENCE", "SIDE");
