-- Old sequences deletion (CGS)

--DROP SEQUENCE "BICOMP"."CGS_CAMT_053_ACCOUNT_STATEMENT_SEQUENCE";
--DROP SEQUENCE "BICOMP"."CGS_CAMT_053_BULK_SEQUENCE";
--DROP SEQUENCE "BICOMP"."CGS_CAMT_053_SERVICE_STATEMENT_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_LAC_BULK_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_LAC_BULK_STATEMENT_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_ENTRY_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_LTIN_BULK_STATEMENT_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_ENTRY_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_PLCR_BULK_STATEMENT_SEQUENCE";
DROP SEQUENCE "BICOMP"."CGS_LMR_SEQUENCE";


-- Old sequences deletion (TIPS)

DROP SEQUENCE "BICOMP"."TIPS_CAMT_052_BANK_ACCOUNT_REPORT_SEQUENCE";
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_ENTRY_SEQUENCE";
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_ACCOUNT_STATEMENT_SEQUENCE";
DROP SEQUENCE "BICOMP"."TIPS_CAMT_053_BANK_STATEMENT_SEQUENCE";
