-- Rename column LT_AMOUNT of table RT1_PSR_PARTICIPANT_BODY

ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY"
RENAME COLUMN "LT_AMOUNT" TO "PAYMENT_AMOUNT";

ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY"
RENAME COLUMN "LT_REFERENCE" TO "PAYMENT_REFERENCE";

ALTER TABLE "BICOMP"."RT1_PSR_PARTICIPANT_BODY"
RENAME COLUMN "LT_STATUS" TO "PAYMENT_STATUS";
